Compare menus
cuappdev/eatery-blue-android pull request #148
Opened 2024-09-27 04:37 UTC by oliviaxjiang

## Problems Addressed

### 1. [Issue #142: Scrolling Header](https://github.com/cuappdev/eatery-blue-android/issues/142)  
✅ **Resolved** by refactoring the EateryDetailsStickerHeader and using it in CompareMenusScreen

### 2. [Issue #141: Sheet Stays Open](https://github.com/cuappdev/eatery-blue-android/issues/141)  
✅ **Fixed** by adding an additional close line to `OnCompareMenusClick`. Did not used NavController or LaunchedEffect

### 3. [Issue #140: Formatting Stuff](https://github.com/cuappdev/eatery-blue-android/issues/140)  
🟡 **Fixed except middle format issue** Figma design is rectangular borders, so idk how to fix

### 4. [Issue #138: Row Clickable](https://github.com/cuappdev/eatery-blue-android/issues/138)  
✅ **Fixed** this issue per the outlined requirements. The app behavior should now match the expected outcome described in the issue.

### 5. [Issue #139 : eatery name bottom padding](https://github.com/cuappdev/eatery-blue-android/issues/138)  
✅ **Fixed** added padding according to figma design

### 6. [Issue #137: Not Done](https://github.com/cuappdev/eatery-blue-android/issues/137)  
🚫 **Not Addressed**: IDK what filter cuts off means.

## View Model Logic Description
CompareMenusBotSheet needs to manage its own states (adding/removing selected eateries/filters) so it gets it's own viewModel (CompareMenusBotViewModel). CompareMenusScreen also needs state management, so it also gets a view model (CompareMenusViewModel). No specific viewmodel logic resides in HomeViewModel or EateryDetailsViewModel as they are all delegated to the two new view models.

## Potential places for change (Would love advice here!)
List<Int> called eateryIds currently gets sent to CompareMenusScreen and CompareMenusScreen has to call a function to pass that information into the viewmodel, may want to used sharedStateHandle and give it directly to CompareMenusViewModel? (I tried looking up on StackOverFlow on how to share states between two screens that is connected via NavController and someone said that the best practice would be sharedViewModel (?))

2024-09-27 20:27 UTC, zachseidner1 requested changes
This is a great first draft! I like your decision to give the compare menus bottom sheet a `ViewModel` and injecting it via `hiltViewModel()`. After seeing all the filtering logic it definitely makes sense. There are a bit of comments that you need to work through, anything, so much so that anything I labeled with "nit" don't feel pressure to fix. But I really appreciate the work you've put into implementing this and I hope you've learned more about Android architecture!

2024-09-27 20:27 UTC, zachseidner1 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/viewmodels/HomeViewModel.kt
Why are we changing this file? All the state for `CompareMenusBottomSheet` should be stored in the `ViewModel` that corresponds to it right?

2024-09-28 02:52 UTC, thisjustin123 reviewed
I'll defer the approval of this PR to zach since his comments are incredibly comprehensive. But I just left some tiny additional comments.

Thanks for the review Zach. U da man.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/components/comparemenus/CompareMenusBotSheet.kt
> +    compareMenusBotViewModel: CompareMenusBotViewModel = hiltViewModel()
Ohhh okay I see what we ended up doing. I like this; a separate viewmodel for the sheet.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/components/comparemenus/CompareMenusBotSheet.kt
> +                            Row(
Ya good point! There's a lot of indentation here.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/components/comparemenus/CompareMenusBotSheet.kt
> +                            Row(
I think it's generally good to take out the header, content, and bottom portions into separate composables for readability.

Veronica discovered this feature where you just highlight a bunch of your function and hit `Extract` that pops up and it does this all for you. I don't know how accurate/good it is though, but perhaps try it out!

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/components/details/EateryDetailsStickyHeader.kt
> +    onItemClick: (Int) -> Unit,
Nice, love the removal of viewmodel.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/components/settings/AppIconBottomSheet.kt
> +                when(it){
I smell unformatted file >:)

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/navigation/MainTabbedNavigation.kt
> +    }
Strange formatting!

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/navigation/MainTabbedNavigation.kt
> +        }
lovely stuff, this passing of IDs is exactly what we need!

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/screens/CompareMenusScreen.kt
Oh god yeah let's split this up.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/viewmodels/CompareMenusBotViewModel.kt
> +    val eateryFlow: StateFlow<EateryApiResponse<List<Eatery>>> =
Yes I agree. Package everything you can into 1 flow for simplicity if you can; that means `compareMenusUiState` should be the only flow exposed.

We used to violate this a lot. We shouldn't do that anymore. It makes UI and flow control a lot harder.

2024-09-28 02:52 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eatery/ui/viewmodels/HomeViewModel.kt
Oh yeah good point... what are all these functions for?

2024-10-02 22:27 UTC, zachseidner1 approved these changes
W

2024-10-03 01:42 UTC, merged