Justin/analytics: Firebase Analytics & Notifications Handling
cuappdev/eatery-blue-android pull request #25
Opened 2022-10-26 21:28 UTC by thisjustin123

**Changes:**
-  Firebase console made for Eatery Blue.
-  Firebase analytics logging has been implemented. All logged actions are: Login, Logout, open Eatery, complete onboarding, favorite eatery, search eatery, open settings screen, report send, order online, directions.
(Can confirm these are being successfully logged in the Eatery Blue Firebase console.)
-  Notifications handling from firebase has been implemented. Notifications from here on out are the responsibility of back-end, so there's not much more to do on frontend until there is a framework for notifications on backend.
Nonetheless, notifications have been tested to work on emulator devices from Firebase.

**Firebase Console Screenshot:**
![image](https://user-images.githubusercontent.com/47724806/198141491-0137afc2-bbf6-4a4d-a688-833ff100a621.png)

**Firebase Notifications Demo:**

https://user-images.githubusercontent.com/47724806/198141670-cd1c51b7-4bd6-488d-9c04-87a70005d92b.mp4

2022-10-26 22:13 UTC, ckdesir requested changes
Looks fire 🔥!!

You may also want to disable analytics from being pinged on the console while you're developing so events don't get mixed up! [This ](https://stackoverflow.com/questions/39558549/disable-firebase-in-development-mode-in-android) outlines how

2022-10-30 19:25 UTC, thisjustin123 commented on app/google-services.json
> +{
Done in commit [6429121](https://github.com/cuappdev/eatery-blue-android/pull/25/commits/6429121686c79e5a6e9f93a358f4a1937e6e756a).

2022-10-30 19:26 UTC, thisjustin123 commented
> Looks fire 🔥!!
> 
> You may also want to disable analytics from being pinged on the console while you're developing so events don't get mixed up! [This ](https://stackoverflow.com/questions/39558549/disable-firebase-in-development-mode-in-android) outlines how

Done in commit [8e2a1f6](https://github.com/cuappdev/eatery-blue-android/pull/25/commits/8e2a1f6e5cfe815c8bacce37afbed05191a61f0c). 

Thanks for linking this forum! Made it very easy to implement.

2022-10-30 23:53 UTC, ckdesir approved these changes

2022-10-31 01:56 UTC, merged