Gregor/login profile account
cuappdev/eatery-blue-android pull request #59
Opened 2024-02-11 03:25 UTC by Gregor-Guerrier

## Overview
Completed the Login and Account portions of Eatery

## Changes Made
Created: `AccountPage.kt`, `LoginToast.kt`
Altered/Refactored: `LoginViewModel.kt`, `ProfileScreen.kt`, `LoginPage.kt`, `EateryDetailsLoading.kt`, `MainTabbedNavigation.kt`, `SettingsScreen.kt`, `colors.xml`

Creation of `AccountPage.kt`:
- Created `AccountPage.kt` from scratch to portray two major sections, how much of each currency the user has, and transactions
- Transactions differentiated by color and symbol to know whether or not it is adding or spending value
- Allows to see transactions for different values provided by Cornell (BRBS, Mealswipes, Citybucks, Laundry)

Creation of `LoginToast.kt`:
- Created `LoginToast.kt` from scratch in order to notify the user of when they are sent a Duo Push, just incase they miss it, also shows if the login is successful

Altered `LoginViewModel.kt`:
- Altered `LoginViewModel.kt` to fit MVVM norms in Jetpack Compose
- Added `State.Login` and `State.Account` which are two states sent through flows in order to know where we should be on the profile page.
- Removed functions and replaced them with: `getTransactionsOfType`, `onNetIDTyped`, `onPasswordTyped`, `onLoginPressed`, `onLoginFailed`, `onLogoutPressed`

Altered `ProfileScreen.kt`:
- Altered `ProfileScreen.kt` to fit MVVM norms by sending the loginViewModel through in order to preserve flows and states
- Chooses between showing `AccountPage.kt` vs `LoginPage.kt` depending on `State`

Altered `LoginPage.kt`:
- Altered `LoginPage.kt` to update `State` according to our login progress
- Actually logs in the user!!!

Altered `EateryDetailsLoading.kt`:
- Altered `EateryDetailsLoading.kt` simply to add ACCOUNT_TYPE to allow the creation of a new Modal

Altered `MainTabbedNavigation.kt`:
- Altered `MainTabbedNavigation.kt` simply to add the creation of the loginViewModel so we are auto logged in when the app is first opened in order to save time.

Altered `SettingsScreen.kt`:
- Altered `SettingsScreen.kt` in order to fix the logout

Altered `colors.xml`:
- Altered `colors.xml` to add more colors (yellow, light yellow, ... etc)

## Test Coverage
Samsung S21

## Screenshots & Videos
https://github.com/cuappdev/eatery-blue-android/assets/36115868/51899b9e-7f45-4a85-be92-1daa37e0b7dc

https://github.com/cuappdev/eatery-blue-android/assets/36115868/0478d898-de51-4234-9921-15586608b722

2024-02-11 18:35 UTC, emilyhu8 reviewed
I just added some comments Justins got the more intense review lol

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/data/models/User.kt
> +    DEPOSIT(3), SPEND(1), NOOP(0), WHAT(2);
please delete the what lol

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/data/repositories/UserRepository.kt
> +    // TODO change this to use get backend?
delete TODO

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/LoginPage.kt
> +//        Text(
delete the commented out text lol

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/viewmodels/LoginViewModel.kt
>              Log.d("LOGIN", e.stackTraceToString())
delete log

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/viewmodels/LoginViewModel.kt
> +    //
missing description?

2024-02-11 18:35 UTC, emilyhu8 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/navigation/MainTabbedNavigation.kt
> +//            val autoLogin = backStackEntry.arguments?.getBoolean("autoLogin")!!
delete comment

2024-02-11 18:44 UTC, thisjustin123 requested changes
HELP!!! PLEASE FIX THIS!

Otherwise very good stuff..

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/data/repositories/UserRepository.kt
> +    // TODO change this to use get backend?
Delete `TODO` to clean up

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/AccountPage.kt
> +                }
Clean up!

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/AccountPage.kt
> +//                )
Clean up!

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/AccountPage.kt
> +fun MealPlanRow(accountName: String, accountType: AccountType, loginViewModel: LoginViewModel) {
Great component! Just rename to something `AccountBalanceRow` since it's being used for things besides Meal Swipes

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/LoginPage.kt
> +//        )
Clean up!

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/components/login/LoginPage.kt
>              ) {
Since you made the `LoginWebView` invisible (which is a lot better than this lol) just delete this so people dont think this works / is necessary lol

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/navigation/MainTabbedNavigation.kt
> +//            val autoLogin = backStackEntry.arguments?.getBoolean("autoLogin")!!
clean up!

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/navigation/MainTabbedNavigation.kt
> +                    }
Try to reverse this logic to make it go to the settings screen if the settings screen is on the back stack. This logic is like reversed and makes no sense cuz the settings screen must be navigated to from the account screen lol

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/viewmodels/LoginViewModel.kt
>  /**
Delete `LoginState` and `LoggedInStatus` since these were artifacts from the previous messy implementation!

2024-02-11 18:44 UTC, thisjustin123 commented on app/src/main/java/com/cornellappdev/android/eateryblue/ui/viewmodels/LoginViewModel.kt
>          private set
Delete, should be made obsolete by new Flow stuff

2024-02-14 22:44 UTC, thisjustin123 approved these changes
LETS FUCKING GO!!!!!!!!!!!

2024-02-21 22:57 UTC, merged